"""SIGIL4CPython experimental typed contracts.

The package is intentionally pure Python and dependency-free. It carries
SIGIL/UAP/KQC guardrail metadata without changing CPython interpreter semantics.
Optional Pydantika and DisCoPy projections live under ``Tools/sigil4cpython``.
"""

from .coherent_sheaf import (
    AgentSpace,
    ChiralPermission,
    CoherentSheafKernel,
    CoherentSheafState,
    IrreducibleResource,
    KernelAgent,
    KernelSurface,
    OuroborosFlow,
    OuroborosPhase,
    PydantikaAnnotation,
    PydantikaCoherentSheaf,
    ReleasePolicy,
    ReleaseScale,
    SCHEMA_ID as PYDANTIKA_COHERENT_SHEAF_SCHEMA_ID,
    SheafGluing,
    TOTAL_CONTEXT,
    build_pydantika_coherent_sheaf,
    compile_pydantika_coherent_sheaf,
)
from .hpc_localized_kernel import (
    ChannelKind,
    CellularFlowMove,
    CellularMoveKind,
    DataflowChannel,
    FPGATargetFamily,
    FPGATargetProfile,
    FPGAResourceKind,
    FPGAResourceProfile,
    HPCLocalizedKernel,
    HPCLocalizedState,
    KernelSpace,
    MorphismKind,
    QuazrisDSLForm,
    QuazrisMorphism,
    QuazrisType,
    SCHEMA_ID as HPC_LOCALIZED_SCHEMA_ID,
    SIGILITAS_CONTEXT,
    SigilAPIInterface,
    VOID_VORTEX_CONTEXT,
    build_hpc_localized_quazris_kernel,
    compile_hpc_localized_quazris_kernel,
)
from .kqc_sheaf import (
    CompilerKernel,
    CompilerStrategy,
    HarmonicConstraint,
    KQCKernelType,
    KQCPublicationSheaf,
    MeasurementProfile,
    PublicationAuthority,
    PublicationHop,
    PullbackWitness,
    RelationKind,
    RepositorySection,
    TQFTCoherenceProfile,
    ThirdWheelFactor,
    TypedRelation,
    UAPState,
    compile_publication_sheaf,
)
from .localization_polyglot import (
    AperiodicCellularTile,
    AperiodicTileKind,
    BindingAuthority,
    LINTER_CANON,
    LexicalNormalization,
    LocalizationRule,
    LocalizationState,
    OpenMPICompliance,
    PolyglotBinding,
    PolyglotLocalizationKernel,
    PolyglotSurface,
    PydantikaSchemaBinding,
    QUANTUM_QUIMBO_CONTEXT,
    SCHEMA_ID as POLYGLOT_LOCALIZATION_SCHEMA_ID,
    SIGIL_GRAPHICAL_CALCULUS,
    SOURCE_URLS as POLYGLOT_SOURCE_URLS,
    SourceDictionaryEntry,
    SourceVocabularyKind,
    UniversalAbstractPipeline,
    build_polyglot_localization_kernel,
    compile_polyglot_localization_kernel,
)
from .paca_estaca_open_pr_presheaf import (
    HOST_SECTION_KEY as PACA_ESTACA_PRESHEAF_HOST_SECTION_KEY,
    KernelDecision as PacaEstacaPresheafDecision,
    Mergeability as PacaEstacaMergeability,
    OpenPullSection,
    PresheafRestriction,
    PullState as PacaEstacaPullState,
    PydantikaOpenPrLedger,
    RelationKind as PacaEstacaLedgerRelationKind,
    REQUIRED_FACETS as PACA_ESTACA_REQUIRED_FACETS,
    SCHEMA_ID as PACA_ESTACA_OPEN_PR_PRESHEAF_SCHEMA_ID,
    SectionRole as PacaEstacaSectionRole,
    TripleCoherence,
    build_reference_open_pr_presheaf,
    compile_reference_open_pr_presheaf,
)
from .uap_wards import (
    DEFAULT_CLAIM_BOUNDARY,
    KokompiledKernel,
    UAPWard,
    UAPWardVerdict,
    build_pacadocencia_uap_kernel,
    check_uap_wards,
    kokompile_kernel,
    validate_kokompiled_kernel,
)
from .virtual_io import (
    CellKind,
    CellularTwistedMove,
    IOCell,
    ResourceAuthority,
    VirtualIOKernel,
    VirtualIOPort,
    VirtualIOProtocol,
    VirtualIOState,
    build_pacaiogame_virtual_rest_kernel,
    compile_virtual_io_kernel,
)

__all__ = [
    "AgentSpace",
    "AperiodicCellularTile",
    "AperiodicTileKind",
    "BindingAuthority",
    "CellKind",
    "CellularFlowMove",
    "CellularTwistedMove",
    "CellularMoveKind",
    "ChannelKind",
    "ChiralPermission",
    "CompilerKernel",
    "CompilerStrategy",
    "CoherentSheafKernel",
    "CoherentSheafState",
    "DEFAULT_CLAIM_BOUNDARY",
    "DataflowChannel",
    "FPGATargetFamily",
    "FPGATargetProfile",
    "FPGAResourceKind",
    "FPGAResourceProfile",
    "HPCLocalizedKernel",
    "HPCLocalizedState",
    "HPC_LOCALIZED_SCHEMA_ID",
    "HarmonicConstraint",
    "IOCell",
    "IrreducibleResource",
    "KQCKernelType",
    "KQCPublicationSheaf",
    "KernelAgent",
    "KernelSpace",
    "KernelSurface",
    "KokompiledKernel",
    "LINTER_CANON",
    "LexicalNormalization",
    "LocalizationRule",
    "LocalizationState",
    "MeasurementProfile",
    "MorphismKind",
    "OpenMPICompliance",
    "OpenPullSection",
    "OuroborosFlow",
    "OuroborosPhase",
    "PACA_ESTACA_OPEN_PR_PRESHEAF_SCHEMA_ID",
    "PACA_ESTACA_PRESHEAF_HOST_SECTION_KEY",
    "PACA_ESTACA_REQUIRED_FACETS",
    "POLYGLOT_LOCALIZATION_SCHEMA_ID",
    "POLYGLOT_SOURCE_URLS",
    "PacaEstacaLedgerRelationKind",
    "PacaEstacaMergeability",
    "PacaEstacaPresheafDecision",
    "PacaEstacaPullState",
    "PacaEstacaSectionRole",
    "PresheafRestriction",
    "PublicationAuthority",
    "PublicationHop",
    "PolyglotBinding",
    "PolyglotLocalizationKernel",
    "PolyglotSurface",
    "PullbackWitness",
    "PYDANTIKA_COHERENT_SHEAF_SCHEMA_ID",
    "PydantikaAnnotation",
    "PydantikaCoherentSheaf",
    "PydantikaOpenPrLedger",
    "PydantikaSchemaBinding",
    "QUANTUM_QUIMBO_CONTEXT",
    "QuazrisDSLForm",
    "QuazrisMorphism",
    "QuazrisType",
    "RelationKind",
    "RepositorySection",
    "ResourceAuthority",
    "ReleasePolicy",
    "ReleaseScale",
    "SIGILITAS_CONTEXT",
    "SIGIL_GRAPHICAL_CALCULUS",
    "SheafGluing",
    "SigilAPIInterface",
    "SourceDictionaryEntry",
    "SourceVocabularyKind",
    "TOTAL_CONTEXT",
    "TQFTCoherenceProfile",
    "ThirdWheelFactor",
    "TripleCoherence",
    "TypedRelation",
    "UAPState",
    "UAPWard",
    "UAPWardVerdict",
    "UniversalAbstractPipeline",
    "VirtualIOKernel",
    "VirtualIOPort",
    "VirtualIOProtocol",
    "VirtualIOState",
    "VOID_VORTEX_CONTEXT",
    "build_hpc_localized_quazris_kernel",
    "build_pacadocencia_uap_kernel",
    "build_pacaiogame_virtual_rest_kernel",
    "build_polyglot_localization_kernel",
    "build_pydantika_coherent_sheaf",
    "build_reference_open_pr_presheaf",
    "check_uap_wards",
    "compile_hpc_localized_quazris_kernel",
    "compile_polyglot_localization_kernel",
    "compile_publication_sheaf",
    "compile_pydantika_coherent_sheaf",
    "compile_reference_open_pr_presheaf",
    "compile_virtual_io_kernel",
    "kokompile_kernel",
    "validate_kokompiled_kernel",
]
